---
# tasks file for ansible_role_powerdns_recursor

# Specific variables
- name: Loading the OS specific variables
  include_vars: "{{ item | basename }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}_{{ ansible_distribution_version | int }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "../vars"
        - "."


# Install packages
- name: Installing packages
  include: "install.yml"

# Setup
#- name: Configuring
#  include: "configure.yml"
